services:
  - docker

before_install:
  - docker build -t kvs/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true kvs/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "hosting-react-app"
  env: "react-app-env"
  bucket_name: "elasticbeanstalk-ap-south-1-765212525841"
  bucket_path: "hosting-react-app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
